
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czmxzrevjtwwbpnpqmxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bXh6cmV2anR3d2JwbnBxbXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjIxNjEsImV4cCI6MjA2MjkzODE2MX0.scZqoP_Y7ARwNFYkk6zkITIVYkorH55aQN0_8pEqHF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
