
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyayvnitqbjecohfihfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5YXl2bml0cWJqZWNvaGZpaGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTk5MjksImV4cCI6MjA2MjA3NTkyOX0.BX836HcAg6hht68qp-2Dp1uUcSKSQjojAqmCVOyZOhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
